name: Build docker image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print environment
        run: |
          echo "The event is ${{ github.event_name }}"
          echo "${GITHUB_REF}"
          echo "${GITHUB_REF##*/}"
      - name: Docker push to tencentyun docker mirror
        if: ${{ github.event_name == 'release' }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gwy15/dtools
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PSWD }}
          tags: "latest"
          tag_semver: true
